name: publish_to_pages_production
inputs:
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare Pages token'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare Account ID'
    required: true
runs:
  using: composite
  steps:
  - name: Publish to cloudflare pages (production)
    env:
      CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
    run: |-
      cd public
      npm i wrangler@3.1.0
      npx wrangler pages deploy . --project-name=docs-deriv-com --branch=main
      echo "New website - REDACTED-docs-deriv-com.pages.dev"
    shell: bash