name: Production Release

on:
  push:
      branches:
          - master
      paths-ignore:
          - '**.md'

jobs:
    release-production:
        timeout-minutes: 40
        runs-on: Ubuntu-latest
        environment: production
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
            - name: Deploy to Cloudflare ☁️
              uses: "deriv-com/shared-actions/.github/actions/publish_to_pages_branch@master"
              with:
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  project_name: docs-deriv-com
                  branch_name: main
                  output_dir: src
                  cname_url: docs-deriv-com.pages.dev
              
