name: Production Release

on:
  push:
      branches:
          - master
      paths-ignore:
          - '**.md'

jobs:
    release-production:
        timeout-minutes: 40
        runs-on: Ubuntu-latest
        environment: production
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

              # For using same tag for staging and production we need to uncomment these two below lines:
              # with:
              #   tagRegex: "production(.*)"
            - name: Deploy to Cloudflare ☁️
              uses: cloudflare/wrangler-action@2.0.0
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy src --project-name=docs-deriv-com --branch=main

            - name: Cloudflare production link ✨
              run: echo "New website - docs-deriv-com.pages.dev"
            
            - name: Slack Notification 📣
              uses: 8398a7/action-slack@v3
              with:
                  status: ${{ job.status }}
                  fields: workflow,repo
                  if_mention: failure,cancelled
                  custom_payload: |
                      {
                        attachments: [{
                          color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                          text: `Release for *Deriv.com* with version *$GIT_TAG_NAME*`
                        }]
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
              if: always()